blog/urls.py
from django.urls import path, include
from . import views
from .models import Blog
# App name of the blog
# To add the name of the url path to any link, 
# you must use the name "Blog:{whichever path name you need to use}" 
app_name="Blog"

urlpatterns = [
    # url path to the main blog view!
    path('blogs/', views.blog_list, name="blog_list"),
]

contact/urls.py
from django.urls import path, include
from . import views
from .models import Contact
# App name of the Contact
# To add the name of the url path to any link within html, 
# you must use the name "Contact:{whichever path name you need to use}" 
app_name= "Contact"

urlpatterns = [
    # url path to the main contact page
    path('', views.contact_list, name="contact_list"),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

###  from rest_framework.urls import urlpatterns as drf_urlpatterns 
# The url file for the django-demo project
urlpatterns = [
    # url for the admin site
    path('admin/', admin.site.urls),
    # url for the Contact app url file
    path('', include('contact.urls')),
    # url for the Blog app url file
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=35, null=False)
    description = models.TextField(max_length=256, null=False)
    pub_date = models.DateField(null=False)
    
    def __str__(self):
        return "{} {} {}".format(self.title,self.description,self.pub_date)

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length=40, null=False)
    last_name = models.CharField(max_length=60, null=False)
    email = models.EmailField(null=False)
    
    def __str__(self):
        return "{} {} {}".format(self.first_name,self.last_name,self.email)

blog/views.py
from django.shortcuts import render, reverse
from .models import Blog
from contact.views import *
# Main blog app view that displays the list of views!
def blog_list(request):
    blogs = Blog.objects.order_by('-pub_date')[:5]
    return render(request,'blog_list.html', {'blogs':blogs})

contact/views.py
from django.shortcuts import render, reverse
from .models import Contact
# Main contact page!
def contact_list(request):
    contacts = Contact.objects.all()
    return render(request,'contact_list.html', {'contacts':contacts})

blog/templates/blog_list.html
{% extends 'index.html' %} {% load static %} {% block content %}
<h1 style="text-align: left">Blogs</h1>

{% for blog in blogs %}
    <h3>{{blog.title}}</h3>
    <p>{{blog.description}}</p>
    <p>{{blog.pub_date}}</p>
{% endfor %}

<a href="{% url 'Contact:contact_list'%}">Contact List</a>
{% endblock content %}

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=yes"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Django-Demo></title>

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="d-flex" id="wrapper">
      <!-- Sidebar -->
      <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading"><a href="{% url 'Contact:contact_list' %}">Django-Demo</div>
        <div class="list-group list-group-flush">
            <a href="{% url 'Contact:contact_list'%}"class="list-group-item list-group-item-action bg-light"
            >Contacts</a>
          <a href="{% url 'Blog:blog_list'%}" class="list-group-item list-group-item-action bg-light">Blogs</a>
          <a href="#" class="list-group-item list-group-item-action bg-light">Status</a>
        </div>
      </div>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
        <nav
          class="navbar navbar-expand-lg navbar-light bg-light border-bottom"
        >
          <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              <li class="nav-item active">
                <a class="nav-link" href="#"
                  >Home <span class="sr-only">(current)</span></a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Django-Demo
                </a>
                <div
                  class="dropdown-menu dropdown-menu-right"
                  aria-labelledby="navbarDropdown"
                >
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </div>
        </nav>

        <div class="container-fluid">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
  </body>
</html>

contact/templates/contact_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div style="text-align: left">
  <table style="width: 100%">
    <tr>
      <th><h1>Contacts</h1></th>
    </tr>
    <tr>
      <th>Firstname</th>
      <th style="text-align: left">Lastname</th>
      <th style="text-align: left">Age</th>
    </tr>
    {% for contact in contacts %}
    <tr>
      <td>{{contact.first_name}}</td>
      <td>{{contact.last_name}}</td>
      <td>{{contact.email}}</td>
    </tr>
    {% endfor %}
  </table>
</div>

<a href="{% url 'Blog:blog_list'%}">Blog List</a>
{% endblock content %}

contact/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=yes"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Django-Demo</title>

    <!-- Bootstrap core CSS -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="d-flex" id="wrapper">
      <!-- Sidebar -->
      <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading"><a href="{% url 'Contact:contact_list' %}">Django-Demo</div>
        <div class="list-group list-group-flush">
          <a href="{% url 'Contact:contact_list'%}"class="list-group-item list-group-item-action bg-light"
            >Contacts</a
          >
          <a href="{% url 'Blog:blog_list'%}" class="list-group-item list-group-item-action bg-light"
            >Blogs</a>
        </div>
      </div>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
        <nav
          class="navbar navbar-expand-lg navbar-light bg-light border-bottom"
        >
          <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'Contact:contact_list'%}"
                  >Home <span class="sr-only">(current)</span></a
                >
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  Django-Demo
                </a>
                <div
                  class="dropdown-menu dropdown-menu-right"
                  aria-labelledby="navbarDropdown"
                >
                  <a class="dropdown-item" href="{% url 'Contact:contact_list'%}">Contacts</a>
                  <a class="dropdown-item" href="{% url 'Blog:blog_list'%}">Blog</a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </div>
        </nav>

        <div class="container-fluid">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
      $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    </script>
  </body>
</html>